### ISSUE TITLE
Database needs to be set up

### ISSUE THREAD

**Issue by kevinmlee** [RZZK/perk#3]

**Comment by zumunis** [comment]
I'm setting up the server today

**Comment by rcidigo** [comment]
UPDATE: Setting up server and database tomorrow morning

**Comment by zumunis** [comment]
The server and database can both be created through amazon web services, I signed up for ec2 web server from amazon, we can set it up tomorrow

**Comment by rcidigo** [comment]
i thought we were using sql???
anyways ok well get everything straight tomorrow

**Comment by zumunis** [comment]
I think you can use sql with ec2, i think thats what kysar was talking about

**Comment by rcidigo** [comment]
oh ok got ya
