### ISSUE TITLE
The create account login can be improved

### ISSUE THREAD

**Issue by rcidigo** [RZZK/perk#7]
Im not sure how you guys feel about the 2x3 table,
but I feel we can make it look a but better. Also maybe a field
for confirm email so that way the user has a chance to catch the mistake
of inputting the wrong email.

**Comment by rcidigo** [comment]
I can work on this kevin if you like???
just let me know

**Comment by kevinmlee** [comment]
Sure. Maybe make it like the design that I showed you earlier? The one
hosted directly from my website

On Sunday, October 18, 2015, rcidigo notifications@github.com wrote:

> I can work on this kevin if you like???
> just let me know
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/RZZK/perk/issues/7#issuecomment-149067386.

## 

_Kevin Lee_

**Comment by rcidigo** [comment]
account login is improved.
